// Package project manages what every Parrot project has, whatever its
// platform: its directory and its manifest, parrot.json. The files of the
// platform's SDK are generated by the platform (see internal/platforms).
package project

import (
	"fmt"
	"regexp"

	"parrot/internal/generator"
)

// validName keeps names usable both as a directory and as the project name
// of the SDK's build system, e.g. CMake's project().
var validName = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]*$`)

// Create creates a new project directory called name, relative to the
// current working directory, with cfg as its parrot.json. It returns the
// paths it created, in creation order. It fails if the name is invalid or the
// directory already exists. The platform then generates its files in it.
func Create(name string, cfg Config) ([]string, error) {
	if !validName.MatchString(name) {
		return nil, fmt.Errorf("invalid project name %q: use letters, digits, '-' and '_'", name)
	}
	if err := generator.CreateDir(name); err != nil {
		return nil, err
	}
	created := []string{name}

	cfgPath, err := writeConfig(name, cfg)
	if err != nil {
		return created, err
	}
	return append(created, cfgPath), nil
}
