package catalog_test

import (
	"strings"
	"testing"

	"parrot/internal/components/catalog"
	"parrot/internal/project"
	"parrot/internal/targets"
)

func entry(t *testing.T, typ, name, config string) project.ComponentConfig {
	t.Helper()
	return project.ComponentConfig{Type: typ, Name: name, Config: []byte(config)}
}

func TestClaims(t *testing.T) {
	esp32, _ := targets.Get("esp32")
	cfg := project.Config{Target: "esp32", Components: []project.ComponentConfig{
		entry(t, "led", "status", `{"pin": 4}`),
		entry(t, "button", "user", `{"pin": 18}`),
		entry(t, "adc", "light", `{"pin": 34}`),
		entry(t, "pwm", "fan", `{"pin": 19, "frequency": 25000}`),
	}}
	claims, err := catalog.Claims(cfg, esp32)
	if err != nil {
		t.Fatal(err)
	}
	wantPins := []int{4, 18, 34, 19}
	for i, c := range claims {
		if c.Component != cfg.Components[i].Name || len(c.GPIOs) != 1 || c.GPIOs[0] != wantPins[i] {
			t.Errorf("claim %d = %+v, want %s on GPIO%d", i, c, cfg.Components[i].Name, wantPins[i])
		}
	}
	if fan := claims[3]; fan.LEDC == nil || fan.LEDC.Frequency != 25000 || fan.LEDC.Resolution != 11 {
		t.Errorf("fan LEDC need = %+v, want 25000 Hz at 11 bits", fan.LEDC)
	}
	if claims[0].LEDC != nil {
		t.Error("an LED should not need LEDC")
	}
}

func TestClaimsErrors(t *testing.T) {
	esp32, _ := targets.Get("esp32")
	tests := []struct {
		entry   project.ComponentConfig
		wantErr string
	}{
		{entry(t, "servo", "arm", `{"pin": 4}`), `component "arm" in parrot.json has unknown type "servo"`},
		{entry(t, "led", "status", `{"pin": 4, "frequency": 5}`), `invalid config for component "status"`},
		{entry(t, "pwm", "fan", `{"pin": 4, "frequency": 0}`), "0 Hz cannot be generated by LEDC on ESP32"},
	}
	for _, tt := range tests {
		_, err := catalog.Claims(project.Config{Components: []project.ComponentConfig{tt.entry}}, esp32)
		if err == nil || !strings.HasPrefix(err.Error(), tt.wantErr) {
			t.Errorf("Claims(%s) error = %v, want prefix %q", tt.entry.Name, err, tt.wantErr)
		}
	}
}

// An I2C bus claims its two GPIOs and a controller.
func TestClaimsI2CBus(t *testing.T) {
	esp32, _ := targets.Get("esp32")
	cfg := project.Config{Target: "esp32", Components: []project.ComponentConfig{
		entry(t, "i2c-bus", "sensors", `{"sda": 21, "scl": 22}`),
	}}
	claims, err := catalog.Claims(cfg, esp32)
	if err != nil {
		t.Fatal(err)
	}
	if c := claims[0]; c.Component != "sensors" || len(c.GPIOs) != 2 || c.GPIOs[0] != 21 || c.GPIOs[1] != 22 || !c.I2CController {
		t.Errorf("claim = %+v, want sensors on GPIO21 and GPIO22 with an I2C controller", c)
	}

	cfg.Components[0] = entry(t, "i2c-bus", "sensors", `{"sda": 21, "scl": 21}`)
	if _, err := catalog.Claims(cfg, esp32); err == nil || err.Error() != "SDA and SCL cannot use the same GPIO" {
		t.Errorf("Claims with SDA == SCL: error = %v", err)
	}
}

// An I2C device claims its address on its bus, and no GPIO or controller.
func TestClaimsI2CDevice(t *testing.T) {
	esp32, _ := targets.Get("esp32")
	cfg := project.Config{Target: "esp32", Components: []project.ComponentConfig{
		entry(t, "i2c-device", "display", `{"bus": "sensors", "address": 60, "frequency": 400000}`),
	}}
	claims, err := catalog.Claims(cfg, esp32)
	if err != nil {
		t.Fatal(err)
	}
	c := claims[0]
	if c.I2CAddress == nil || c.I2CAddress.Bus != "sensors" || c.I2CAddress.Address != 0x3C {
		t.Errorf("claim = %+v, want address 0x3C on sensors", c)
	}
	if len(c.GPIOs) != 0 || c.I2CController || c.LEDC != nil {
		t.Errorf("claim = %+v, want no GPIO, controller or LEDC", c)
	}
}

// A BME280 claims the device it drives, and none of the GPIOs, controller or
// address its device and bus already claim.
func TestClaimsBME280(t *testing.T) {
	esp32, _ := targets.Get("esp32")
	cfg := project.Config{Target: "esp32", Components: []project.ComponentConfig{
		entry(t, "i2c-bus", "sensors", `{"sda": 21, "scl": 22}`),
		entry(t, "i2c-device", "environment_device", `{"bus": "sensors", "address": 118, "frequency": 400000}`),
		entry(t, "sensor-bme280", "environment", `{"device": "environment_device"}`),
	}}
	claims, err := catalog.Claims(cfg, esp32)
	if err != nil {
		t.Fatal(err)
	}
	c := claims[2]
	if c.Component != "environment" || c.Drives != "environment_device" {
		t.Errorf("claim = %+v, want environment driving environment_device", c)
	}
	if len(c.GPIOs) != 0 || c.I2CController || c.I2CAddress != nil || c.LEDC != nil {
		t.Errorf("claim = %+v, want no GPIO, controller, address or LEDC", c)
	}

	cfg.Components[2] = entry(t, "sensor-bme280", "environment", `{"device": "environment_device", "address": 118}`)
	if _, err := catalog.Claims(cfg, esp32); err == nil || !strings.HasPrefix(err.Error(), `invalid config for component "environment"`) {
		t.Errorf("Claims with an address in the sensor's config: error = %v", err)
	}
}
