// Package pwm is the generic PWM output component, built on the ESP-IDF LEDC
// peripheral. The user gives a GPIO and a frequency; Parrot picks the duty
// resolution and allocates the LEDC timer and channel.
package pwm

import (
	"fmt"
	"strings"

	"parrot/internal/components"
	"parrot/internal/resources"
	"parrot/internal/targets"
)

// Type is the component type used in the CLI and in parrot.json.
const Type = "pwm"

// preferredResolution is the duty resolution used whenever the frequency allows it.
const preferredResolution = 13

// PWM is a PWM output on a GPIO.
type PWM struct {
	Name string // canonical component name, also the C symbol prefix
	Config
}

// Config is the PWM entry in parrot.json.
type Config struct {
	Pin       int `json:"pin"`
	Frequency int `json:"frequency"` // Hz
}

// Needs reports the resources a PWM output uses: its GPIO and a LEDC channel
// whose timer runs at the configured frequency and resolution.
func (c Config) Needs(target targets.Target) (resources.Needs, error) {
	resolution, err := Resolution(target, c.Frequency)
	if err != nil {
		return resources.Needs{}, err
	}
	return resources.Needs{
		GPIOs: []int{c.Pin},
		LEDC:  &resources.LEDCTimer{Frequency: c.Frequency, Resolution: resolution},
	}, nil
}

// New builds a PWM from user-supplied values, normalizing the name.
func New(name string, pin, frequency int) (PWM, error) {
	normalized, err := components.NormalizeName(name)
	if err != nil {
		return PWM{}, err
	}
	if frequency <= 0 {
		return PWM{}, fmt.Errorf("frequency must be positive, got %d Hz", frequency)
	}
	return PWM{Name: normalized, Config: Config{Pin: pin, Frequency: frequency}}, nil
}

// Resolution returns the duty resolution for frequency on target: 13 bits if
// a LEDC timer can produce that combination, otherwise the closest resolution
// that works (lower for high frequencies, higher for very low ones).
func Resolution(target targets.Target, frequency int) (int, error) {
	best := 0
	for r := 1; r <= target.LEDC.MaxResolution; r++ {
		if target.LEDC.TimerFits(frequency, r) && (best == 0 || distance(r) < distance(best)) {
			best = r
		}
	}
	if best == 0 {
		return 0, fmt.Errorf("%d Hz cannot be generated by LEDC on %s", frequency, target.DisplayName)
	}
	return best, nil
}

func distance(resolution int) int {
	if resolution > preferredResolution {
		return resolution - preferredResolution
	}
	return preferredResolution - resolution
}

// MaxDuty is the raw LEDC duty for 100%. ESP-IDF accepts duties in
// [0, 2^resolution], except that 2^resolution is invalid when the timer uses
// its maximum resolution.
func MaxDuty(target targets.Target, resolution int) uint32 {
	if resolution == target.LEDC.MaxResolution {
		return 1<<resolution - 1
	}
	return 1 << resolution
}

// templateData is what the PWM templates see. LEDC values are ESP-IDF symbols.
type templateData struct {
	Name       string // C symbol prefix, e.g. "fan"
	Macro      string // C macro prefix, e.g. "FAN"
	Target     string // e.g. "ESP32"
	Pin        int
	Frequency  int
	Bits       int    // duty resolution
	Resolution string // ledc_timer_bit_t, e.g. "LEDC_TIMER_13_BIT"
	Timer      string // ledc_timer_t, e.g. "LEDC_TIMER_0"
	Channel    string // ledc_channel_t, e.g. "LEDC_CHANNEL_0"
	Clock      string // ledc_clk_cfg_t, from the target
	MaxDuty    uint32
}

// Create generates the component under projectDir/components/<name>, using
// the LEDC timer and channel allocated to it, and returns the paths it created.
func Create(projectDir string, p PWM, target targets.Target, ledc resources.LEDCAssignment) ([]string, error) {
	// The enums are named LEDC_TIMER_<n>, LEDC_CHANNEL_<n> and LEDC_TIMER_<n>_BIT
	// on every target (hal/ledc_types.h); the allocator stays within the
	// target's timer and channel counts and Resolution within its bit width.
	data := templateData{
		Name:       p.Name,
		Macro:      strings.ToUpper(p.Name),
		Target:     target.DisplayName,
		Pin:        p.Pin,
		Frequency:  p.Frequency,
		Bits:       ledc.Resolution,
		Resolution: fmt.Sprintf("LEDC_TIMER_%d_BIT", ledc.Resolution),
		Timer:      fmt.Sprintf("LEDC_TIMER_%d", ledc.Timer),
		Channel:    fmt.Sprintf("LEDC_CHANNEL_%d", ledc.Channel),
		Clock:      target.LEDC.ClockSource,
		MaxDuty:    MaxDuty(target, ledc.Resolution),
	}
	return components.Generate(projectDir, Type, p.Name, data)
}
