package pwm_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"parrot/internal/components/pwm"
	"parrot/internal/resources"
	"parrot/internal/targets"
)

func mustTarget(t *testing.T, id string) targets.Target {
	t.Helper()
	target, err := targets.Get(id)
	if err != nil {
		t.Fatal(err)
	}
	return target
}

func TestNew(t *testing.T) {
	p, err := pwm.New("Motor-Speed", 4, 5000)
	if err != nil {
		t.Fatal(err)
	}
	if p.Name != "motor_speed" || p.Pin != 4 || p.Frequency != 5000 {
		t.Errorf("New = %+v", p)
	}
	for _, freq := range []int{0, -100} {
		if _, err := pwm.New("test", 4, freq); err == nil {
			t.Errorf("New with frequency %d succeeded, want error", freq)
		}
	}
}

func TestValidate(t *testing.T) {
	tests := []struct {
		target  string
		config  pwm.Config
		wantErr string // empty: valid
	}{
		{"esp32", pwm.Config{Pin: 4, Frequency: 5000}, ""},
		{"esp32-c3", pwm.Config{Pin: 8, Frequency: 5000}, ""},
		{"esp32", pwm.Config{Pin: 34, Frequency: 5000}, "GPIO34 cannot be used as an output on ESP32"},
		{"esp32-c3", pwm.Config{Pin: 50, Frequency: 5000}, "GPIO50 is not available on ESP32-C3"},
		{"esp32", pwm.Config{Pin: 6, Frequency: 5000}, "GPIO6 is reserved for the SPI flash on ESP32"},
		{"esp32", pwm.Config{Pin: 4, Frequency: 50_000_000}, "50000000 Hz cannot be generated by LEDC on ESP32"},
	}
	for _, tt := range tests {
		err := pwm.Validate(mustTarget(t, tt.target), tt.config)
		switch {
		case tt.wantErr == "" && err != nil:
			t.Errorf("Validate(%s, %+v) = %v, want nil", tt.target, tt.config, err)
		case tt.wantErr != "" && (err == nil || err.Error() != tt.wantErr):
			t.Errorf("Validate(%s, %+v) = %v, want %q", tt.target, tt.config, err, tt.wantErr)
		}
	}
}

func TestResolution(t *testing.T) {
	tests := []struct {
		target    string
		frequency int
		want      int // 0: impossible
	}{
		{"esp32", 5000, 13},
		{"esp32-c3", 5000, 13},
		{"esp32-s3", 5000, 13},
		{"esp32-c6", 5000, 13},
		{"esp32", 25_000, 11},    // 80 MHz / 25 kHz = 3200 ticks -> 11 bits
		{"esp32", 20_000_000, 2}, // 80 MHz / 20 MHz = 4 ticks -> 2 bits
		{"esp32", 40_000_000, 1}, // the fastest LEDC output
		{"esp32", 1, 17},         // needs 17 bits to keep the divider in range
		{"esp32-c6", 1, 17},      // 20-bit timers, like ESP32
		{"esp32-c3", 5, 14},      // only possible at C3's maximum resolution
		{"esp32-c3", 1, 0},       // 14-bit timers cannot go that low
		{"esp32-s3", 4, 0},       // same limit as C3
		{"esp32", 80_000_000, 0}, // would need 0 bits
	}
	for _, tt := range tests {
		got, err := pwm.Resolution(mustTarget(t, tt.target), tt.frequency)
		if tt.want == 0 {
			if err == nil {
				t.Errorf("Resolution(%s, %d) = %d, want error", tt.target, tt.frequency, got)
			}
			continue
		}
		if err != nil || got != tt.want {
			t.Errorf("Resolution(%s, %d) = %d, %v; want %d", tt.target, tt.frequency, got, err, tt.want)
		}
	}
}

func TestMaxDuty(t *testing.T) {
	esp32, c3 := mustTarget(t, "esp32"), mustTarget(t, "esp32-c3")
	if got := pwm.MaxDuty(esp32, 13); got != 8192 {
		t.Errorf("MaxDuty(esp32, 13) = %d, want 8192 (2^13)", got)
	}
	if got := pwm.MaxDuty(c3, 14); got != 16383 {
		t.Errorf("MaxDuty(c3, 14) = %d, want 16383 (2^14 - 1 at max resolution)", got)
	}
}

func TestCreate(t *testing.T) {
	dir := t.TempDir()
	p := pwm.PWM{Name: "motor_speed", Config: pwm.Config{Pin: 4, Frequency: 5000}}
	ledc := resources.LEDCAssignment{Timer: 1, Channel: 2, LEDCTimer: resources.LEDCTimer{Frequency: 5000, Resolution: 13}}

	tests := []struct {
		target string
		clock  string
	}{
		{"esp32", "LEDC_USE_APB_CLK"},
		{"esp32-c6", "LEDC_USE_PLL_DIV_CLK"},
	}
	for _, tt := range tests {
		projectDir := filepath.Join(dir, tt.target)
		created, err := pwm.Create(projectDir, p, mustTarget(t, tt.target), ledc)
		if err != nil {
			t.Fatal(err)
		}
		if len(created) != 4 {
			t.Fatalf("created %d paths, want 4: %v", len(created), created)
		}
		base := filepath.Join(projectDir, "components", "motor_speed")
		contains := map[string][]string{
			"motor_speed.c": {
				"#define MOTOR_SPEED_GPIO       4",
				"#define MOTOR_SPEED_MODE       LEDC_LOW_SPEED_MODE",
				"#define MOTOR_SPEED_TIMER      LEDC_TIMER_1",
				"#define MOTOR_SPEED_CHANNEL    LEDC_CHANNEL_2",
				"#define MOTOR_SPEED_FREQUENCY  5000",
				"#define MOTOR_SPEED_RESOLUTION LEDC_TIMER_13_BIT",
				"#define MOTOR_SPEED_CLOCK      " + tt.clock,
				"#define MOTOR_SPEED_MAX_DUTY   8192U",
				"ledc_update_duty(MOTOR_SPEED_MODE, MOTOR_SPEED_CHANNEL)",
			},
			"include/motor_speed.h": {
				"#include <stdint.h>",
				"void motor_speed_init(void);",
				"void motor_speed_set_duty(uint32_t duty_percent);",
				"void motor_speed_stop(void);",
			},
			"CMakeLists.txt": {"PRIV_REQUIRES esp_driver_ledc"},
		}
		for file, snippets := range contains {
			data, err := os.ReadFile(filepath.Join(base, file))
			if err != nil {
				t.Fatal(err)
			}
			for _, s := range snippets {
				if !strings.Contains(string(data), s) {
					t.Errorf("%s: %s does not contain %q", tt.target, file, s)
				}
			}
		}
	}
}
